DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT
(
    id int GENERATED ALWAYS AS IDENTITY(START WITH 100) primary key,
    name VARCHAR(250) NOT NULL
);

CREATE TABLE EMPLOYEE
(
    id INT GENERATED ALWAYS AS IDENTITY(START WITH 100) PRIMARY KEY,
    full_name VARCHAR(250) NOT NULL,
    date_of_birth DATE NOT NULL,
    salary DECIMAL DEFAULT NULL,
    department_id INT NOT NULL,
    FOREIGN KEY (department_id) references DEPARTMENT
);